# Class -- 13 Numpy

# NumPy is the fundamental package for scientific comuting in python.It is a Python library that provides a multidemenional array obeject,various derived objects(such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,includibg mathemaatical,logical,shape manipulation,sortig,selecting ,I/O ,discreate Fourier transforms,basic linear algebra,basic staticstical operations,random simulation and much more.

# Ndarray is the n-dimesional array object defined in the onject defibed in the numpy which stores the collection of the similar type of elements.In the other words,we can define a ndarrry as the collection of the data type (dtype) obects.

# The ndarray object can be accesssed by using the 0 based indexing.Ecah element of the array obejct contains the same size in the memory.

In [12]:
import numpy as np
a = np.array([1,'2',0.8,3])
print(a)
print(type(a))
# String,Float,Integer --- "Upcasting"

['1' '2' '0.8' '3']
<class 'numpy.ndarray'>


In [3]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
a = np.array([1,2,3,4] ,ndmin = 2)
print(a)

[[1 2 3 4]]


In [5]:
a = np.array([1,2,3,4] ,dtype = float)
print(a)

[1. 2. 3. 4.]


# Class - 14

In [5]:
# ndarray.shape --- This attribute return a tuple consisting of array dimenions.It can also be used to resize the array.
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

# Attribute
a.shape = (3,2)
print(a)

# Function
b = a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
# It returns the array with the all zeros

x = np.zeros((2,3),dtype=int) # By default float
print(x)

y = np.ones(5,dtype=int)
print(y)
print(y.ndim)

print(y.size)

[[0 0 0]
 [0 0 0]]
[1 1 1 1 1]
1
5


In [20]:
x = 2.5*(np.ones((2,3)))
print(x)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]]


In [21]:
z = np.eye(5)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(np.diag(c))

d = np.diag([4,2,9,6])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[[4 0 0 0]
 [0 2 0 0]
 [0 0 9 0]
 [0 0 0 6]]


In [30]:
matrix1 = np.array([[1,2],[3,4]])
print("2x2 Matrix:\n",matrix1)

matrix2 = np.array([[1,2,5],[3,4,6],[7,8,9]])
print("3x3 Matrix:\n",matrix2)

2x2 Matrix:
 [[1 2]
 [3 4]]
3x3 Matrix:
 [[1 2 5]
 [3 4 6]
 [7 8 9]]


In [31]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[11,22,33],[44,55,66],[77,88,99]])
matrix3 = matrix1 + matrix2
print(matrix3)

[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]


In [32]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[11,22],[44,55],[77,88]])
matrix3 = np.dot(matrix1,matrix2)
print(matrix3)

[[330 396]
 [726 891]]


In [33]:
# Transpose fucntion
# Syntax -- np.transpose()

matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.transpose(matrix1)
print(matrix2)

[[1 4]
 [2 5]
 [3 6]]


In [40]:
# numpy--- np.arange
a = np.arange(24)
c = a.ndim
print(a)


y = (np.arange(10,22,2)).reshape(2,3)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[10 12 14]
 [16 18 20]]


In [ ]:
# Comaparison between LIST and ARRAY

# 3 Benifits of array:-
# Take less memory
# Fast
# Convininent

In [41]:
import sys
import time

sys.getsizeof(100)

28

In [43]:
l = range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [44]:
a = np.arange(200000)
print(a.itemsize)
print()

print(a.itemsize*len(a))

4

800000


In [46]:
a1 = range(1000000)
b1 = range(1000000)
start = time.time()
c1 = [(x+y) for x,y in zip(a1,b1)]
print("time taken:",(time.time()-start)*1000)

time taken: 117.68460273742676


In [48]:
a1 = np.arange(1000000)
a2 = np.arange(1000000)

start = time.time()
c2 = a1+a2
print("time taken by array :",(time.time()-start)*1000)

time taken by array : 1.9960403442382812


In [49]:
n1 = np.arange(100)
n2 = np.arange(100)

n1 * n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [54]:
# Shallow and Deep Copy

l = [1,2,3,4]
l1 = l
print(l1)
l1[2] = 100

l1 

[1, 2, 3, 4]


[1, 2, 100, 4]

In [55]:
l

[1, 2, 100, 4]

In [56]:
l1

[1, 2, 100, 4]

In [57]:
print(id(l),id(l1))

1933463721216 1933463721216


In [58]:
l2 = l.copy()
l2[1] = 100

In [59]:
l2 

[1, 100, 100, 4]

In [60]:
l

[1, 2, 100, 4]

In [61]:
print(id(l),id(l2))

1933463721216 1933463915200
