# Class -- 13 Numpy

# NumPy is the fundamental package for scientific comuting in python.It is a Python library that provides a multidemenional array obeject,various derived objects(such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,includibg mathemaatical,logical,shape manipulation,sortig,selecting ,I/O ,discreate Fourier transforms,basic linear algebra,basic staticstical operations,random simulation and much more.

# Ndarray is the n-dimesional array object defined in the onject defibed in the numpy which stores the collection of the similar type of elements.In the other words,we can define a ndarrry as the collection of the data type (dtype) obects.

# The ndarray object can be accesssed by using the 0 based indexing.Ecah element of the array obejct contains the same size in the memory.

In [8]:
import numpy as np
a = np.array([1,'2',0.8,3])
print(a)
print(type(a))
# String,Float,Integer --- "Upcasting"

['1' '2' '0.8' '3']
<class 'numpy.ndarray'>


In [9]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
a = np.array([1,2,3,4] ,ndmin = 2)
print(a)

[[1 2 3 4]]


In [11]:
a = np.array([1,2,3,4] ,dtype = float)
print(a)

[1. 2. 3. 4.]


# Class - 14

In [12]:
# ndarray.shape --- This attribute return a tuple consisting of array dimenions.It can also be used to resize the array.
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

# Attribute
a.shape = (3,2)
print(a)

# Function
b = a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [13]:
# It returns the array with the all zeros

x = np.zeros((2,3),dtype=int) # By default float
print(x)

y = np.ones(5,dtype=int)
print(y)
print(y.ndim)

print(y.size)

[[0 0 0]
 [0 0 0]]
[1 1 1 1 1]
1
5


In [14]:
x = 2.5*(np.ones((2,3)))
print(x)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]]


In [15]:
z = np.eye(5)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(np.diag(c))

d = np.diag([4,2,9,6])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[[4 0 0 0]
 [0 2 0 0]
 [0 0 9 0]
 [0 0 0 6]]


In [17]:
matrix1 = np.array([[1,2],[3,4]])
print("2x2 Matrix:\n",matrix1)

matrix2 = np.array([[1,2,5],[3,4,6],[7,8,9]])
print("3x3 Matrix:\n",matrix2)

2x2 Matrix:
 [[1 2]
 [3 4]]
3x3 Matrix:
 [[1 2 5]
 [3 4 6]
 [7 8 9]]


In [18]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[11,22,33],[44,55,66],[77,88,99]])
matrix3 = matrix1 + matrix2
print(matrix3)

[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]


In [19]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[11,22],[44,55],[77,88]])
matrix3 = np.dot(matrix1,matrix2)
print(matrix3)

[[330 396]
 [726 891]]


In [20]:
# Transpose fucntion
# Syntax -- np.transpose()

matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.transpose(matrix1)
print(matrix2)

[[1 4]
 [2 5]
 [3 6]]


In [21]:
# numpy--- np.arange
a = np.arange(24)
c = a.ndim
print(a)


y = (np.arange(10,22,2)).reshape(2,3)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[10 12 14]
 [16 18 20]]


In [22]:
# Comaparison between LIST and ARRAY

# 3 Benifits of array:-
# Take less memory
# Fast
# Convininent

In [23]:
import sys
import time

sys.getsizeof(100)

28

In [24]:
l = range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [25]:
a = np.arange(200000)
print(a.itemsize)
print()

print(a.itemsize*len(a))

4

800000


In [26]:
a1 = range(1000000)
b1 = range(1000000)
start = time.time()
c1 = [(x+y) for x,y in zip(a1,b1)]
print("time taken:",(time.time() - start)*1000)# intial it comes in nano second so t convert it into micro multiply with 1000.

time taken: 153.7320613861084


In [40]:
a1 = np.arange(1000000)
a2 = np.arange(1000000)
start = time.time()
c2 = a1+a2
print("time taken by array :",(time.time()- start)*1000)

time taken by array : 3.989696502685547


In [28]:
n1 = np.arange(100)
n2 = np.arange(100)

n1 * n2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [29]:
# Shallow and Deep Copy

l = [1,2,3,4]
l1 = l
print(l1)
l1[2] = 100

l1 

[1, 2, 3, 4]


[1, 2, 100, 4]

In [30]:
l

[1, 2, 100, 4]

In [31]:
l1

[1, 2, 100, 4]

In [32]:
print(id(l),id(l1))

2429963255360 2429963255360


In [33]:
l2 = l.copy()
l2[1] = 100

In [34]:
l2 

[1, 100, 100, 4]

In [35]:
l

[1, 2, 100, 4]

In [36]:
print(id(l),id(l2))

2429963255360 2429929268480


In [7]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [8]:
l2=l.copy()
l2

[[1, 2, 3], [4, 5, 6]]

In [11]:
l2[0][2] = 100
l2

[[1, 2, 100], [4, 5, 6]]

In [13]:
l

[[1, 2, 100], [4, 5, 6]]

In [18]:
import copy
l = [[1,2,3],[4,5,6]]
l2 = copy.deepcopy(l)
l2[0][2] = 100

In [19]:
l2

[[1, 2, 100], [4, 5, 6]]

In [20]:
l

[[1, 2, 3], [4, 5, 6]]

# Class - 15

In [3]:
# numpy.hstack() function --- Horizontally stack numpy arrays using numpy.hstack()
import numpy as np

x = np.array((3,5,7))
print(x)
y = np.array((5,7,9))
print(y)

print(np.hstack((x,y)))

x1 = np.array([[3],[4],[5]])
print(x1)
y2 = np.array([[5],[7],[9]])
print(y2)

print(np.hstack((x,y)))

[3 5 7]
[5 7 9]
[3 5 7 5 7 9]
[[3]
 [4]
 [5]]
[[5]
 [7]
 [9]]
[3 5 7 5 7 9]


In [5]:
# numpy.vstack() function --- Horizontally stack numpy arrays using numpy.hstack()
import numpy as np

x = np.array((3,5,7))
print(x)
y = np.array((5,7,9))
print(y)

print(np.vstack((x,y)))

x1 = np.array([[3],[4],[5]])
print(x1)
y2 = np.array([[5],[7],[9]])
print(y2)

print(np.vstack((x,y)))

[3 5 7]
[5 7 9]
[[3 5 7]
 [5 7 9]]
[[3]
 [4]
 [5]]
[[5]
 [7]
 [9]]
[[3 5 7]
 [5 7 9]]


In [21]:
# generate random integer from 0 to 9
random_number = np.random.randint(0,10)
print(random_number)

4


In [22]:
from numpy import random
random_number = random.randint(0,10)
print(random_number)


6


In [23]:
# generate random float-point number between 0 and 1
random_number = np.random.rand()
print(random_number)

0.6033411809912075


In [24]:
interger_array = np.random.randint(0,10,5)
print(interger_array)

[1 6 0 4 2]


In [25]:
float_array = np.random.rand(4)
print(float_array)

[0.16495054 0.71777409 0.89537866 0.02465744]


In [27]:
result = np.random.randint(0,10,(3,4))
print("\n 2D Random Integer Array:\n",result)


 2D Random Integer Array:
 [[5 3 9 3]
 [7 2 5 7]
 [1 0 1 6]]


In [28]:
array1 = np.array([1,2,3,4,5])
random_choice = np.random.choice(array1)
print(random_choice)

5


In [30]:
x = np.random.rand(3,4)
print(x)
x.mean()

[[0.56512934 0.92779461 0.85597734 0.84075068]
 [0.52682465 0.00644007 0.45099911 0.29155414]
 [0.04693347 0.44415454 0.87722115 0.77297341]]


0.5505627090620762

In [32]:
x = np.random.randint(100,300,20).reshape(10,2)
print(x)

[[276 137]
 [277 232]
 [117 294]
 [187 255]
 [160 298]
 [196 294]
 [183 272]
 [280 280]
 [142 147]
 [186 155]]


In [33]:
y = np.random.randint(1,100,(3,3))
print(y)

[[38 42 72]
 [50 17 50]
 [39 80 71]]


In [34]:
np.random.randint

<function RandomState.randint>

In [38]:
from numpy.random import randint as ri

np.random.seed(25)
ri(1,100,(5,6))




array([[ 5, 63, 91, 16, 62, 24],
       [45, 51,  9, 29,  5, 90],
       [32, 70,  2, 40,  4, 89],
       [56,  4, 85, 46,  4,  2],
       [23, 32, 49, 48, 74, 17]])

In [40]:
np.random.seed(100)
M = ri(1,100,(5,6)).reshape(6,5)
M

array([[ 9, 25, 68, 88, 80],
       [49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35],
       [25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28],
       [ 5, 32,  2, 14, 84]])

In [42]:
np.sort(M)

array([[ 9, 25, 68, 80, 88],
       [11, 49, 53, 95, 99],
       [15, 35, 54, 67, 99],
       [16, 17, 25, 59, 61],
       [ 3, 10, 28, 87, 94],
       [ 2,  5, 14, 32, 84]])

In [44]:
np.sort(M,axis=1)

array([[ 9, 25, 68, 80, 88],
       [11, 49, 53, 95, 99],
       [15, 35, 54, 67, 99],
       [16, 17, 25, 59, 61],
       [ 3, 10, 28, 87, 94],
       [ 2,  5, 14, 32, 84]])

In [49]:
a = ri(1,100,(6,5))
b = a.reshape(10,3)
a

array([[22, 26, 55,  7, 38],
       [59, 40, 95, 52, 31],
       [67, 25, 56, 18, 46],
       [90, 46, 36, 17, 13],
       [87, 83, 68, 93, 96],
       [21, 11,  9, 90, 73]])

In [58]:
b

array([[22, 26, 55],
       [ 7, 38, 59],
       [40, 95, 52],
       [31, 67, 25],
       [56, 18, 46],
       [90, 46, 36],
       [17, 13, 87],
       [83, 68, 93],
       [96, 21, 11],
       [ 9, 90, 73]])

In [51]:
a.max()

96

In [52]:
a.min()

7

In [53]:
a.argmax()

24

In [54]:
b.max()

96

In [55]:
b.min()

7

In [57]:
b.max(axis=0)# row-wise maximum

array([96, 95, 93])

In [59]:
b.max(axis=1)# column-wise maximum

array([55, 59, 95, 67, 56, 90, 87, 93, 96, 90])

In [60]:
b.argmax(axis=1)

array([2, 2, 1, 1, 0, 0, 2, 2, 0, 1], dtype=int64)

In [61]:
x = np.array([[1,2,3,4,5],[12,34,4,5,6],[65,76,7,8,9],[1,3,44,55,5],[7,56,4,6,66]])
print(x)

[[ 1  2  3  4  5]
 [12 34  4  5  6]
 [65 76  7  8  9]
 [ 1  3 44 55  5]
 [ 7 56  4  6 66]]


In [62]:
x[1:3,1:3]

array([[34,  4],
       [76,  7]])

In [65]:
x[1:4,2:4]

array([[ 4,  5],
       [ 7,  8],
       [44, 55]])

In [ ]:
a = np.arange(1,21)
print(a)

a>10

In [67]:
a>10

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [66]:
a[a>10]

array([22, 26, 55, 38, 59, 40, 95, 52, 31, 67, 25, 56, 18, 46, 90, 46, 36,
       17, 13, 87, 83, 68, 93, 96, 21, 11, 90, 73])

In [68]:
a[a < 10]

array([7, 9])

In [69]:
a[a%2 == 0]

array([22, 26, 38, 40, 52, 56, 18, 46, 90, 46, 36, 68, 96, 90])

In [70]:
a[a%2 !=0]

array([55,  7, 59, 95, 31, 67, 25, 17, 13, 87, 83, 93, 21, 11,  9, 73])

In [71]:
a[a==5]

array([], dtype=int32)

In [73]:
a[a%2!= 0] = 0
a

array([[22, 26,  0,  0, 38],
       [ 0, 40,  0, 52,  0],
       [ 0,  0, 56, 18, 46],
       [90, 46, 36,  0,  0],
       [ 0,  0, 68,  0, 96],
       [ 0,  0,  0, 90,  0]])

In [85]:
a = np.array((1,2,3,4,2,5))
print(a)


[1 2 3 4 2 5]


In [86]:
a.ndim

1

In [87]:
a.shape

(6,)

In [88]:
x = np.where(a==2)
x

(array([1, 4], dtype=int64),)

In [89]:
np.where(a<4)

(array([0, 1, 2, 4], dtype=int64),)

In [93]:
x = np.array([1,2,3,4,5,6,10,12,15])
np.searchsorted(x,8)
x

array([ 1,  2,  3,  4,  5,  6, 10, 12, 15])